### ISSUE TITLE
Duplicitní texty u představení a popisu představení

### ISSUE THREAD

**Issue by ondrejfreedom** [ReadyPlayerNaN/polocas-napadu-api#4]
Pro představení jsou 3? různé text - popis představení, krátký popis formátu a dlouhý popis formátu.
Často se asi stane, že popis představení bude odpovídat krátkému popisu formátu. V detailu představení to pak vede k tomu, že je tam dvakrát za sebou jeden a ten samý text.
Možná vyřešit to tak, že pokud se nevyplní popis představení, použije se defaultně popis formátu?

**Comment by ReadyPlayerNaN** [comment]
Jop, to dává smysl. Popis představení by měl být dobrovolný. U činoher by takový popis byl vyloženě vzácný.
